general {
    lock_cmd = pidof hyprlock || hyprlock      # avoid starting multiple hyprlock instances
    before_sleep_cmd = pidof hyprlock || hyprlock # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # avoid pressing a key twice to wake the display
}

listener {
    timeout = 300                              # 5min
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 330                              # 5.5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
